import "normalize.css/normalize.css";
import "./globals.css";

import localFont from "next/font/local";
import Header from "./components/header/header";
import Footer from "./components/footer/footer";

import "./globals.css";

const steppe = localFont({
  src: "./fonts/steppe-regular.ttf",
  variable: "--font-steppe",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={steppe.variable}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
